# サイト基本情報
title: Claude実践ラボ
description: Claudeを活用した資料作成・プログラミング・サービス開発の実践ガイド
baseurl: "/claude-dev-lab-jp"
url: "https://Mechanicalgoat.github.io"
github_username: Mechanicalgoat
lang: ja

# テーマ設定
theme: minima
# remote_theme: jekyll/minima 
minima:
  skin: classic

# プラグイン設定
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ナビゲーション設定
header_pages:
  - about.md
  - categories.md
  - tags.md

# 記事設定
permalink: /:year/:month/:day/:title/
timezone: Asia/Tokyo

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts/
  - .gitignore
sass:
  style: compressed
liquid:
  error_mode: strict
# 画像関連設定
default_image: "/claude-dev-lab-jp/assets/images/og-default.jpg"
default_thumbnail: "/claude-dev-lab-jp/assets/images/thumbnails/default-thumb.png"
logo_image: "/claude-dev-lab-jp/assets/images/logo.png"

# 画像サイズ設定
thumbnail_width: 800
thumbnail_height: 450
og_image_width: 1200
og_image_height: 630

# 自動サムネイル生成の有効化
auto_thumbnail: true
