name: 週次コンテンツ更新
on:
  schedule:
    - cron: '0 1 * * 1,4'  # 月曜と木曜の午前1時（UTC）= 日本時間10時
  workflow_dispatch:  # 手動実行用

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 全履歴を取得

      - name: Gitコンフィグを設定
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Pythonをセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 依存パッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown pandas beautifulsoup4 anthropic

      - name: データを収集
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub APIへのアクセス用
        run: python scripts/collect_data.py

      - name: コンテンツを生成
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: python scripts/generate_content.py

      - name: 変更の確認
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: 変更をコミットしてプッシュ
        if: steps.check-changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git commit -m "コンテンツ更新 $(date +%Y-%m-%d)"
          git push origin HEAD:main
