name: 週次コンテンツ更新

on:
  schedule:
    - cron: '0 1 * * 1,4'  # 月曜と木曜の午前1時（UTC）= 日本時間10時
  workflow_dispatch:  # 手動実行用
  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 依存パッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown
          - name: データを収集
        run: python scripts/collect_data.py
        
      - name: コンテンツを生成
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: python scripts/generate_content.py
        - name: 変更をコミットしてプッシュ
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "コンテンツ更新 $(date +%Y-%m-%d)"
          git push
          cron: '0 1 * * 1,4'  # 好みの頻度に変更
          pip install requests markdown pandas beautifulsoup4  # 必要なパッケージを追加
          - name: 追加の処理
  run: python scripts/your_custom_script.py